travis:
  secure:
    BINSTAR_TOKEN: XO+oBzgfgLqELm4MNAB6f6PZvTzXvAsyIIzvIHlqVFt2FhFiNsUXjt6NE0LsX9yVmHNmlOXc6FQAEylUPEXYbEPWNgE88/Ag4rvI4LayKoWpdQBTuhou0OqaYrZZRxehvcby2g7eUEuD20JojdCz1FSxbRJdDXW2CiiZLTwdEO+TNyZtHnK3KCSYnsVMDndr0xU0qZ5oaK1X8VUIul88xK+V4i6LegMGP7CUyul0orKaV1L93Ii8/jj1Um5dCxe9H6ax/IRrBpm8KUVHF1CjK/wbEYgRVOPy/f+pP2Jyd9jGqOvi/B6eyb3JuRe0m+jxbFFSIjd7HSJ2krI7ano/arwp5BqJ5OIJN/0cNU01iLVj9VtKE1VfRr4WYnvB87yZtYP00TS+3EYfoJ8zjLjsJ1vwBQ9KsYwK3txcUodHg+6DgVykOphJ1rNjFDdFrL1tcwAJESEV+0P96ZLU69lObgescLBf1nJlPRTzlMq3pMAGOHM7RlSpi5SUrBYyvsXthM6OfZKdFvkxsq8XaZUFtbxnOFFGLGrMkIBD13dSn3VC32KqcHPr6YNe0srDSj5yCLIgs3yNsneCqEyu90E/US0wEGMO09r4Mzx+ZQHLNh/J9uWnGeaAr2UKDFxQuCgcrrE/weMwmEJgLStwfv0GXuARnCkugeT4olT3o6K1Irc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
